// Generated by CoffeeScript 1.4.0
(function() {
  var AMEX, AdaptiveCardFormatter, AmexCardFormatter, DefaultCardFormatter, determineCardType, _ref;

  AmexCardFormatter = require('./amex_card_formatter');

  DefaultCardFormatter = require('./default_card_formatter');

  _ref = require('./card_utils'), determineCardType = _ref.determineCardType, AMEX = _ref.AMEX;

  AdaptiveCardFormatter = (function() {

    function AdaptiveCardFormatter() {
      this.amexCardFormatter = new AmexCardFormatter();
      this.defaultCardFormatter = new DefaultCardFormatter();
      this.formatter = this.defaultCardFormatter;
    }

    AdaptiveCardFormatter.prototype.format = function(pan) {
      return this.formatter.format(pan);
    };

    AdaptiveCardFormatter.prototype.parse = function(text, error) {
      return this.formatter.parse(text, error);
    };

    AdaptiveCardFormatter.prototype.isChangeValid = function(change) {
      if (determineCardType(change.proposed.text.replace(/[^\d]+/g, '')) === AMEX) {
        this.formatter = this.amexCardFormatter;
      } else {
        this.formatter = this.defaultCardFormatter;
      }
      return this.formatter.isChangeValid(change);
    };

    return AdaptiveCardFormatter;

  })();

  module.exports = AdaptiveCardFormatter;

}).call(this);
