// Generated by CoffeeScript 1.4.0
(function() {
  var AMEX, AdaptiveCardFormatter, AmexCardFormatter, DISCOVER, DefaultCardFormatter, MASTERCARD, VISA, determineCardType;

  AmexCardFormatter = require('./amex_card_formatter');

  DefaultCardFormatter = require('./default_card_formatter');

  AMEX = 'amex';

  DISCOVER = 'discover';

  MASTERCARD = 'mastercard';

  VISA = 'visa';

  determineCardType = function(pan) {
    var firsttwo, halfiin, iin;
    if (pan == null) {
      return null;
    }
    pan = pan.toString();
    firsttwo = parseInt(pan.slice(0, 2), 10);
    iin = parseInt(pan.slice(0, 6), 10);
    halfiin = parseInt(pan.slice(0, 3), 10);
    if (pan[0] === '4') {
      return VISA;
    } else if (pan.slice(0, 4) === '6011' || firsttwo === 65 || (halfiin >= 664 && halfiin <= 649) || (iin >= 622126 && iin <= 622925)) {
      return DISCOVER;
    } else if (firsttwo >= 51 && firsttwo <= 55) {
      return MASTERCARD;
    } else if (firsttwo === 34 || firsttwo === 37) {
      return AMEX;
    }
  };

  AdaptiveCardFormatter = (function() {

    function AdaptiveCardFormatter() {
      this.amexCardFormatter = new AmexCardFormatter();
      this.defaultCardFormatter = new DefaultCardFormatter();
      this.formatter = this.defaultCardFormatter;
    }

    AdaptiveCardFormatter.prototype.format = function(pan) {
      return this.formatter.format(pan);
    };

    AdaptiveCardFormatter.prototype.parse = function(text, error) {
      return this.formatter.parse(text, error);
    };

    AdaptiveCardFormatter.prototype.isChangeValid = function(change) {
      if (determineCardType(change.proposed.text.replace(/[^\d]+/g, '')) === AMEX) {
        this.formatter = this.amexCardFormatter;
      } else {
        this.formatter = this.defaultCardFormatter;
      }
      return this.formatter.isChangeValid(change);
    };

    return AdaptiveCardFormatter;

  })();

  module.exports = AdaptiveCardFormatter;

}).call(this);
