// Generated by CoffeeScript 1.6.1
(function() {
  var AmexCardFormatter, DefaultCardFormatter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DefaultCardFormatter = require('./default_card_formatter');

  AmexCardFormatter = (function(_super) {

    __extends(AmexCardFormatter, _super);

    function AmexCardFormatter() {
      return AmexCardFormatter.__super__.constructor.apply(this, arguments);
    }

    AmexCardFormatter.prototype.maximumLength = 15 + 2;

    AmexCardFormatter.prototype.hasDelimiterAtIndex = function(index) {
      return index === 4 || index === 11;
    };

    return AmexCardFormatter;

  })(DefaultCardFormatter);

  module.exports = AmexCardFormatter;

}).call(this);
