// Generated by CoffeeScript 1.4.0
(function() {
  var AMEX_SPACE_INDEXES, AmexCardFormatter, DefaultCardFormatter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DefaultCardFormatter = require('./default_card_formatter');

  AMEX_SPACE_INDEXES = [4, 10];

  if (typeof Object.freeze === "function") {
    Object.freeze(AMEX_SPACE_INDEXES);
  }

  AmexCardFormatter = (function(_super) {

    __extends(AmexCardFormatter, _super);

    AmexCardFormatter.prototype.cardLength = 15;

    function AmexCardFormatter() {
      this.spaceIndexes = AMEX_SPACE_INDEXES.slice();
    }

    return AmexCardFormatter;

  })(DefaultCardFormatter);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = AmexCardFormatter;
  } else {
    this.AmexCardFormatter = AmexCardFormatter;
  }

}).call(this);
