// Generated by CoffeeScript 1.4.0
(function() {
  var AdaptiveCardFormatter, CardTextField, TextField, determineCardType,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TextField = require('./text_field');

  AdaptiveCardFormatter = require('./adaptive_card_formatter');

  determineCardType = require('./card_utils').determineCardType;

  CardTextField = (function(_super) {

    __extends(CardTextField, _super);

    function CardTextField(element) {
      CardTextField.__super__.constructor.call(this, element);
      this.setFormatter(new AdaptiveCardFormatter());
    }

    CardTextField.prototype.cardType = function() {
      return determineCardType(this.value());
    };

    return CardTextField;

  })(TextField);

  module.exports = CardTextField;

}).call(this);
