// Generated by CoffeeScript 1.6.2
(function() {
  var AMEX, DISCOVER, MASTERCARD, VISA, determineCardType, luhnCheck, validCardLength;

  AMEX = 'amex';

  DISCOVER = 'discover';

  MASTERCARD = 'mastercard';

  VISA = 'visa';

  determineCardType = function(pan) {
    var firsttwo, halfiin, iin;

    if (pan == null) {
      return null;
    }
    pan = pan.toString();
    firsttwo = parseInt(pan.slice(0, 2), 10);
    iin = parseInt(pan.slice(0, 6), 10);
    halfiin = parseInt(pan.slice(0, 3), 10);
    if (pan[0] === '4') {
      return VISA;
    } else if (pan.slice(0, 4) === '6011' || firsttwo === 65 || (halfiin >= 664 && halfiin <= 649) || (iin >= 622126 && iin <= 622925)) {
      return DISCOVER;
    } else if (firsttwo >= 51 && firsttwo <= 55) {
      return MASTERCARD;
    } else if (firsttwo === 34 || firsttwo === 37) {
      return AMEX;
    }
  };

  luhnCheck = function(pan) {
    var digit, flip, i, sum, _i, _ref;

    sum = 0;
    flip = true;
    for (i = _i = _ref = pan.length - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
      if (!(pan.charAt(i) !== ' ')) {
        continue;
      }
      digit = parseInt(pan.charAt(i), 10);
      sum += (flip = !flip) ? Math.floor((digit * 2) / 10) + Math.floor(digit * 2 % 10) : digit;
    }
    return sum % 10 === 0;
  };

  validCardLength = function(pan) {
    var _ref;

    switch (determineCardType(pan)) {
      case VISA:
        return (_ref = pan.length) === 13 || _ref === 16;
      case DISCOVER:
      case MASTERCARD:
        return pan.length === 16;
      case AMEX:
        return pan.length === 15;
      default:
        return false;
    }
  };

  module.exports = {
    determineCardType: determineCardType,
    luhnCheck: luhnCheck,
    validCardLength: validCardLength,
    AMEX: AMEX,
    DISCOVER: DISCOVER,
    MASTERCARD: MASTERCARD,
    VISA: VISA
  };

}).call(this);
