// Generated by CoffeeScript 1.4.0
(function() {
  var DelimitedTextFormatter, ExpiryDateFormatter, zpad2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DelimitedTextFormatter = require('./delimited_text_formatter');

  zpad2 = function(n) {
    var result;
    result = "" + n;
    while (result.length < 2) {
      result = "0" + result;
    }
    return result;
  };

  ExpiryDateFormatter = (function(_super) {

    __extends(ExpiryDateFormatter, _super);

    function ExpiryDateFormatter() {
      return ExpiryDateFormatter.__super__.constructor.apply(this, arguments);
    }

    ExpiryDateFormatter.prototype.delimiter = '/';

    ExpiryDateFormatter.prototype.maximumLength = 5;

    ExpiryDateFormatter.prototype.hasDelimiterAtIndex = function(index) {
      return index === 2;
    };

    ExpiryDateFormatter.prototype.format = function(value) {
      var month, year;
      if (!value) {
        return '';
      }
      month = value.month, year = value.year;
      year = year % 10;
      return ExpiryDateFormatter.__super__.format.call(this, zpad2(month) + zpad2(year));
    };

    ExpiryDateFormatter.prototype.parse = function(text) {
      var match;
      text = ExpiryDateFormatter.__super__.parse.call(this, text);
      if (match = text.match(/^(0?[1-9]|1\d)(\d\d)$/)) {
        return {
          month: Number(match[1]),
          year: Number(match[2])
        };
      }
    };

    ExpiryDateFormatter.prototype.isChangeValid = function(change) {
      var isBackspace, match, newText;
      isBackspace = change.proposed.text.length < change.current.text.length;
      newText = change.proposed.text;
      if (isBackspace) {
        if (change.deleted.text === this.delimiter) {
          newText = newText[0];
        }
        if (newText === '0') {
          newText = '';
        }
      } else if (change.inserted.text === this.delimiter && change.current.text === '1') {
        newText = "01" + this.delimiter;
      } else if (!/^\d$/.test(change.inserted.text)) {
        return false;
      } else {
        if (/^[2-9]$/.test(newText)) {
          newText = '0' + newText;
        }
        if (/^1[3-9]$/.test(newText)) {
          return false;
        }
        if (newText === '00') {
          return false;
        }
        if (/^(0[1-9]|1[0-2])$/.test(newText)) {
          newText += this.delimiter;
        }
        if ((match = newText.match(/^(\d\d)(.)(\d\d?).*$/)) && match[2] === this.delimiter) {
          newText = match[1] + this.delimiter + match[3];
        }
      }
      change.proposed.text = newText;
      change.proposed.caret = {
        start: newText.length,
        end: newText.length
      };
      return true;
    };

    return ExpiryDateFormatter;

  })(DelimitedTextFormatter);

  module.exports = ExpiryDateFormatter;

}).call(this);
