// Generated by CoffeeScript 1.6.2
(function() {
  var Formatter;

  Formatter = (function() {
    function Formatter() {}

    Formatter.prototype.maximumLength = null;

    Formatter.prototype.format = function(text) {
      if (text == null) {
        text = '';
      }
      if (this.maximumLength != null) {
        text = text.substring(0, this.maximumLength);
      }
      return text;
    };

    Formatter.prototype.parse = function(text, error) {
      if (text == null) {
        text = '';
      }
      if (this.maximumLength != null) {
        text = text.substring(0, this.maximumLength);
      }
      return text;
    };

    Formatter.prototype.isChangeValid = function(change, error) {
      var available, newText, selectedRange, text, truncatedLength, _ref;

      _ref = change.proposed, selectedRange = _ref.selectedRange, text = _ref.text;
      if ((this.maximumLength != null) && text.length > this.maximumLength) {
        available = this.maximumLength - (text.length - change.inserted.text.length);
        newText = change.current.text.substring(0, change.current.selectedRange.start);
        if (available > 0) {
          newText += change.inserted.text.substring(0, available);
        }
        newText += change.current.text.substring(change.current.selectedRange.start + change.current.selectedRange.length);
        truncatedLength = text.length - newText.length;
        change.proposed.text = newText;
        selectedRange.start -= truncatedLength;
      }
      return true;
    };

    return Formatter;

  })();

  module.exports = Formatter;

}).call(this);
