// Generated by CoffeeScript 1.4.0
(function() {
  var FormattedTextField, KEYS, isWordChar,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  KEYS = {
    A: 65,
    ZERO: 48,
    NINE: 57,
    LEFT: 37,
    RIGHT: 39,
    UP: 38,
    DOWN: 40,
    BACKSPACE: 8,
    DELETE: 46
  };

  KEYS.isDigit = function(keyCode) {
    return (this.ZERO <= keyCode && keyCode <= this.NINE);
  };

  KEYS.isDirectional = function(keyCode) {
    return keyCode === this.LEFT || keyCode === this.RIGHT || keyCode === this.UP || keyCode === this.DOWN;
  };

  isWordChar = function(char) {
    return char && /^\w$/.test(char);
  };

  FormattedTextField = (function() {

    FormattedTextField.prototype.selectionDirection = null;

    function FormattedTextField(element) {
      this.element = element;
      this.click = __bind(this.click, this);

      this.keyUp = __bind(this.keyUp, this);

      this.keyPress = __bind(this.keyPress, this);

      this.keyDown = __bind(this.keyDown, this);

      this.element.on('keydown', this.keyDown);
      this.element.on('keypress', this.keyPress);
      this.element.on('keyup', this.keyUp);
      this.element.on('click', this.click);
    }

    FormattedTextField.prototype.insertCharacter = function(event) {
      var caret;
      event.preventDefault();
      if (this.hasSelection) {
        this.clearSelection();
      }
      if (this.formatter.length && this.text.length >= this.formatter.length) {
        return;
      }
      this.replaceSelection(String.fromCharCode(event.charCode));
      caret = this.caret;
      caret.start = caret.end;
      return this.caret = caret;
    };

    FormattedTextField.prototype.moveUp = function(event) {
      event.preventDefault();
      this.caret = {
        start: 0,
        end: 0
      };
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.moveUpAndModifySelection = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
        case null:
          caret.start = 0;
          break;
        case 'right':
          caret.end = caret.start;
          caret.start = 0;
      }
      this.caret = caret;
      return this.selectionDirection = caret.start === caret.end ? null : 'left';
    };

    FormattedTextField.prototype.moveDown = function(event) {
      var end;
      end = this.text.length;
      event.preventDefault();
      this.caret = {
        start: end,
        end: end
      };
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.moveDownAndModifySelection = function(event) {
      var caret, end;
      caret = this.caret;
      end = this.text.length;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
          caret.start = caret.end;
          caret.end = end;
          break;
        case 'right':
        case null:
          caret.end = end;
      }
      this.caret = caret;
      return this.selectionDirection = caret.start === caret.end ? null : 'right';
    };

    FormattedTextField.prototype.moveLeft = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      if (this.hasSelection) {
        caret.end = caret.start;
      } else {
        caret.start--;
        caret.end--;
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.moveLeftAndModifySelection = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
        case null:
          this.selectionDirection = 'left';
          caret.start--;
          break;
        case 'right':
          caret.end--;
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.moveWordLeft = function(event) {
      var index;
      event.preventDefault();
      index = this.lastWordBreakBeforeIndex(this.caret.start - 1);
      this.caret = {
        start: index,
        end: index
      };
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.moveWordLeftAndModifySelection = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
        case null:
          this.selectionDirection = 'left';
          caret.start = this.lastWordBreakBeforeIndex(caret.start - 1);
          break;
        case 'right':
          caret.end = this.lastWordBreakBeforeIndex(caret.end);
          if (caret.end < caret.start) {
            caret.end = caret.start;
          }
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.moveRight = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      if (this.hasSelection) {
        caret.start = caret.end;
      } else {
        caret.start++;
        caret.end++;
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.moveRightAndModifySelection = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
          caret.start++;
          break;
        case 'right':
        case null:
          this.selectionDirection = 'right';
          caret.end++;
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.moveWordRight = function(event) {
      var index;
      event.preventDefault();
      index = this.nextWordBreakAfterIndex(this.caret.end);
      this.caret = {
        start: index,
        end: index
      };
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.moveWordRightAndModifySelection = function(event) {
      var caret;
      caret = this.caret;
      event.preventDefault();
      switch (this.selectionDirection) {
        case 'left':
          caret.start = this.nextWordBreakAfterIndex(caret.start);
          if (caret.start > caret.end) {
            caret.start = caret.end;
          }
          break;
        case 'right':
        case null:
          this.selectionDirection = 'right';
          caret.end = this.nextWordBreakAfterIndex(caret.end);
      }
      this.caret = caret;
      if (caret.start === caret.end) {
        return this.selectionDirection = null;
      }
    };

    FormattedTextField.prototype.deleteBackward = function(event) {
      var caret;
      event.preventDefault();
      if (!this.hasSelection) {
        caret = this.caret;
        caret.start--;
        this.caret = caret;
      }
      return this.clearSelection();
    };

    FormattedTextField.prototype.deleteWordBackward = function(event) {
      var caret;
      if (this.hasSelection) {
        return this.deleteBackward(event);
      }
      event.preventDefault();
      caret = this.caret;
      caret.start = this.lastWordBreakBeforeIndex(caret.start - 1);
      this.caret = caret;
      return this.clearSelection();
    };

    FormattedTextField.prototype.deleteBackwardByDecomposingPreviousCharacter = function(event) {
      return this.deleteBackward(event);
    };

    FormattedTextField.prototype.deleteForward = function(event) {
      var caret;
      event.preventDefault();
      if (!this.hasSelection) {
        caret = this.caret;
        caret.end++;
        this.caret = caret;
      }
      return this.clearSelection();
    };

    FormattedTextField.prototype.deleteWordForward = function(event) {
      var caret;
      if (this.hasSelection) {
        return this.deleteForward(event);
      }
      caret = this.caret;
      event.preventDefault();
      caret.end = this.nextWordBreakAfterIndex(caret.end);
      this.caret = caret;
      return this.clearSelection();
    };

    FormattedTextField.prototype.__defineGetter__('hasSelection', function() {
      var caret;
      caret = this.caret;
      return caret.start !== caret.end;
    });

    FormattedTextField.prototype.lastWordBreakBeforeIndex = function(index) {
      var indexes, result, wordBreakIndex, _i, _len;
      indexes = this.leftWordBreakIndexes;
      result = indexes[0];
      for (_i = 0, _len = indexes.length; _i < _len; _i++) {
        wordBreakIndex = indexes[_i];
        if (index > wordBreakIndex) {
          result = wordBreakIndex;
        } else {
          break;
        }
      }
      return result;
    };

    FormattedTextField.prototype.__defineGetter__('leftWordBreakIndexes', function() {
      var i, result, text, _i, _ref;
      result = [];
      text = this.text;
      for (i = _i = 0, _ref = text.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (!isWordChar(text[i - 1]) && isWordChar(text[i])) {
          result.push(i);
        }
      }
      return result;
    });

    FormattedTextField.prototype.nextWordBreakAfterIndex = function(index) {
      var indexes, result, wordBreakIndex, _i, _len;
      indexes = this.rightWordBreakIndexes.reverse();
      result = indexes[0];
      for (_i = 0, _len = indexes.length; _i < _len; _i++) {
        wordBreakIndex = indexes[_i];
        if (index < wordBreakIndex) {
          result = wordBreakIndex;
        } else {
          break;
        }
      }
      return result;
    };

    FormattedTextField.prototype.__defineGetter__('rightWordBreakIndexes', function() {
      var i, result, text, _i, _ref;
      result = [];
      text = this.text;
      for (i = _i = 0, _ref = text.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (isWordChar(text[i]) && !isWordChar(text[i + 1])) {
          result.push(i + 1);
        }
      }
      return result;
    });

    FormattedTextField.prototype.clearSelection = function() {
      return this.replaceSelection('');
    };

    FormattedTextField.prototype.replaceSelection = function(replacement) {
      var caret, text;
      caret = this.caret;
      text = this.text;
      text = text.substring(0, caret.start) + replacement + text.substring(caret.end);
      caret.end = caret.start + replacement.length;
      this.text = text;
      this.caret = caret;
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.selectAll = function(event) {
      var text;
      event.preventDefault();
      text = this.text;
      this.caret = {
        start: 0,
        end: text.length
      };
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.keyDown = function(event) {
      var _this = this;
      return this.rollbackInvalidChanges(function() {
        var altKey, ctrlKey, keyCode, metaKey, shiftKey;
        keyCode = event.keyCode, metaKey = event.metaKey, ctrlKey = event.ctrlKey, shiftKey = event.shiftKey, altKey = event.altKey;
        if ((metaKey || ctrlKey) && keyCode === KEYS.A) {
          _this.selectAll(event);
        } else if (metaKey || ctrlKey) {
          (function() {});
        } else if (KEYS.isDirectional(keyCode)) {
          switch (keyCode) {
            case KEYS.LEFT:
              if (shiftKey && altKey) {
                _this.moveWordLeftAndModifySelection(event);
              } else if (shiftKey) {
                _this.moveLeftAndModifySelection(event);
              } else if (altKey) {
                _this.moveWordLeft(event);
              } else {
                _this.moveLeft(event);
              }
              break;
            case KEYS.RIGHT:
              if (shiftKey && altKey) {
                _this.moveWordRightAndModifySelection(event);
              } else if (shiftKey) {
                _this.moveRightAndModifySelection(event);
              } else if (altKey) {
                _this.moveWordRight(event);
              } else {
                _this.moveRight(event);
              }
              break;
            case KEYS.UP:
              if (shiftKey) {
                _this.moveUpAndModifySelection(event);
              } else {
                _this.moveUp(event);
              }
              break;
            case KEYS.DOWN:
              if (shiftKey) {
                _this.moveDownAndModifySelection(event);
              } else {
                _this.moveDown(event);
              }
          }
        } else if (keyCode === KEYS.BACKSPACE) {
          if (altKey) {
            _this.deleteWordBackward(event);
          } else if (ctrlKey) {
            _this.deleteBackwardByDecomposingPreviousCharacter(event);
          } else {
            _this.deleteBackward(event);
          }
        } else if (keyCode === KEYS.DELETE) {
          if (altKey) {
            _this.deleteWordForward(event);
          } else {
            _this.deleteForward(event);
          }
        }
        return null;
      });
    };

    FormattedTextField.prototype.keyPress = function(event) {
      var _this = this;
      return this.rollbackInvalidChanges(function() {
        return _this.insertCharacter(event);
      });
    };

    FormattedTextField.prototype.keyUp = function(event) {};

    FormattedTextField.prototype.rollbackInvalidChanges = function(callback) {
      var change, ctext, deleted, i, inserted, ptext, result, sharedPrefixLength, sharedSuffixLength, _i, _j, _ref, _ref1;
      change = {
        field: this,
        current: {
          caret: this.caret,
          text: this.text
        }
      };
      result = callback();
      change.proposed = {
        caret: this.caret,
        text: this.text
      };
      if (change.proposed.text !== change.current.text) {
        ctext = change.current.text;
        ptext = change.proposed.text;
        sharedPrefixLength = ctext.length;
        sharedSuffixLength = ctext.length;
        for (i = _i = 0, _ref = ctext.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          if (ptext[i] !== ctext[i]) {
            sharedPrefixLength = i;
            break;
          }
        }
        for (i = _j = 0, _ref1 = ctext.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          if (ptext[ptext.length - 1 - i] !== ctext[ctext.length - 1 - i]) {
            sharedSuffixLength = i;
            break;
          }
        }
        inserted = {
          start: sharedPrefixLength,
          end: ptext.length - sharedSuffixLength
        };
        deleted = {
          start: sharedPrefixLength,
          end: ctext.length - sharedSuffixLength
        };
        inserted.text = ptext.substring(inserted.start, inserted.end);
        deleted.text = ctext.substring(deleted.start, deleted.end);
        change.inserted = inserted;
        change.deleted = deleted;
      }
      if (typeof this.formatter.isChangeValid === 'function') {
        if (this.formatter.isChangeValid(change)) {
          this.text = change.proposed.text;
          this.caret = change.proposed.caret;
        } else {
          this.text = change.current.text;
          this.caret = change.current.caret;
        }
        if (!this.hasSelection) {
          this.selectionDirection = null;
        }
      }
      return result;
    };

    FormattedTextField.prototype.click = function(event) {
      return this.selectionDirection = null;
    };

    FormattedTextField.prototype.on = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.element).on.apply(_ref, args);
    };

    FormattedTextField.prototype.off = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.element).off.apply(_ref, args);
    };

    FormattedTextField.prototype.__defineGetter__('text', function() {
      return this.element.val();
    });

    FormattedTextField.prototype.__defineSetter__('text', function(text) {
      return this.element.val(text);
    });

    FormattedTextField.prototype.__defineGetter__('value', function() {
      var value;
      value = this.element.val();
      if (!this._formatter) {
        return value;
      }
      return this._formatter.parse(value);
    });

    FormattedTextField.prototype.__defineSetter__('value', function(value) {
      if (this._formatter) {
        value = this._formatter.format(value);
      }
      this.element.val("" + value);
      return this.element.trigger('change');
    });

    FormattedTextField.prototype.__defineGetter__('formatter', function() {
      return this._formatter;
    });

    FormattedTextField.prototype.__defineSetter__('formatter', function(formatter) {
      var value;
      value = this.value;
      this._formatter = formatter;
      return this.value = value;
    });

    FormattedTextField.prototype.__defineGetter__('caret', function() {
      var end, start, _ref;
      _ref = this.element.caret(), start = _ref.start, end = _ref.end;
      return {
        start: start,
        end: end
      };
    });

    FormattedTextField.prototype.__defineSetter__('caret', function(caret) {
      var max, min;
      min = 0;
      max = this.text.length;
      caret = {
        start: Math.max(min, Math.min(max, caret.start)),
        end: Math.max(min, Math.min(max, caret.end))
      };
      return this.element.caret(caret);
    });

    FormattedTextField.prototype.__defineGetter__('selectionAnchor', function() {
      switch (this.selectionDirection) {
        case 'left':
          return this.caret.end;
        case 'right':
          return this.caret.start;
        default:
          return null;
      }
    });

    return FormattedTextField;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = FormattedTextField;
  } else if (typeof window !== "undefined" && window !== null) {
    window.FormattedTextField = FormattedTextField;
  }

}).call(this);
