// Generated by CoffeeScript 1.6.1
(function() {
  var DelimitedTextFormatter, SocialSecurityNumberFormatter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DelimitedTextFormatter = require('./delimited_text_formatter');

  SocialSecurityNumberFormatter = (function(_super) {

    __extends(SocialSecurityNumberFormatter, _super);

    function SocialSecurityNumberFormatter() {
      return SocialSecurityNumberFormatter.__super__.constructor.apply(this, arguments);
    }

    SocialSecurityNumberFormatter.prototype.delimiter = '-';

    SocialSecurityNumberFormatter.prototype.maximumLength = 9 + 2;

    SocialSecurityNumberFormatter.prototype.hasDelimiterAtIndex = function(index) {
      return index === 3 || index === 6;
    };

    SocialSecurityNumberFormatter.prototype.isChangeValid = function(change) {
      if (/^\d*$/.test(change.inserted.text)) {
        return SocialSecurityNumberFormatter.__super__.isChangeValid.call(this, change);
      } else {
        return false;
      }
    };

    return SocialSecurityNumberFormatter;

  })(DelimitedTextFormatter);

  module.exports = SocialSecurityNumberFormatter;

}).call(this);
