// Generated by CoffeeScript 1.4.0
(function() {
  var DelimitedTextFormatter, SocialSecurityNumberFormatter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof require !== "undefined" && require !== null) {
    DelimitedTextFormatter = require('./delimited_text_formatter');
  } else {
    DelimitedTextFormatter = this.FieldKit.DelimitedTextFormatter;
  }

  SocialSecurityNumberFormatter = (function(_super) {

    __extends(SocialSecurityNumberFormatter, _super);

    function SocialSecurityNumberFormatter() {
      return SocialSecurityNumberFormatter.__super__.constructor.apply(this, arguments);
    }

    SocialSecurityNumberFormatter.prototype.delimiter = '-';

    SocialSecurityNumberFormatter.prototype.maximumLength = 11;

    SocialSecurityNumberFormatter.prototype.hasDelimiterAtIndex = function(index) {
      return index === 3 || index === 6;
    };

    return SocialSecurityNumberFormatter;

  })(DelimitedTextFormatter);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = SocialSecurityNumberFormatter;
  } else {
    (this.FieldKit || (this.FieldKit = {})).SocialSecurityNumberFormatter = SocialSecurityNumberFormatter;
  }

}).call(this);
