// Generated by CoffeeScript 1.4.0
(function() {
  var DelimitedTextFormatter, UsPhoneFormatter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  DelimitedTextFormatter = require('./delimited_text_formatter');

  UsPhoneFormatter = (function(_super) {

    __extends(UsPhoneFormatter, _super);

    UsPhoneFormatter.prototype.delimiterHash = {
      0: '(',
      4: ')',
      5: ' ',
      9: '-'
    };

    UsPhoneFormatter.prototype.isDelimiter = function(char) {
      var delimiter, index;
      return __indexOf.call((function() {
        var _ref, _results;
        _ref = this.delimiterHash;
        _results = [];
        for (index in _ref) {
          delimiter = _ref[index];
          _results.push(delimiter);
        }
        return _results;
      }).call(this), char) >= 0;
    };

    function UsPhoneFormatter() {}

    UsPhoneFormatter.prototype.delimiterAt = function(index) {
      return this.delimiterHash[index] || '';
    };

    UsPhoneFormatter.prototype.hasDelimiterAtIndex = function(index) {
      return !!this.delimiterAt(index);
    };

    return UsPhoneFormatter;

  })(DelimitedTextFormatter);

  module.exports = UsPhoneFormatter;

}).call(this);
